### ISSUE TITLE
nstlist in apoa1_nvt.mdp 

### ISSUE THREAD

**Issue by songyongshun** [HanatoK/Apoa1-Benchmark#1]
nstlist in apoa1_nvt.mdp is set to 400, this is a little too large. 
I test it in Gromacs/2019.5 version with 2 nodes (32 cores per node), it failed to run.
The error is: 
```
There is no domain decomposition for 56 ranks that is compatible with the
given box and a minimum cell size of 2.9275 nm.

```
since 8 ranks are assigned to PME calculations.
I fixed this by changing nstlist from 400 to 40.

**Comment by HanatoK** [comment]
@songyongshun Thank you for your comment! At the time when I was running the benchmarks, NAMD3.0 was still in early alpha stage which required `stepsPerCycle` to be a fixed value, such as `400`, so for a fair comparison, I also set `nstlist` in GMX to `400`.

The benchmark was conducted on GMX 2020, and I have just checked that the following command is still OK for GMX 2021.6:
```
gmx mdrun -ntomp 1 -nb gpu -pme gpu -bonded gpu -update gpu -gpu_id 1 -s ./apoa1_nvt.tpr
```

GMX 2019 may be too old and does not support `-update gpu`.

For more information, please refer to https://manual.gromacs.org/documentation/current/user-guide/mdrun-performance.html, where `nstlist` is suggested to 200 or 300.

**Comment by songyongshun** [comment]
Thanks for explaination in details. It helps a lot!
