### ISSUE TITLE
margin in apoa1_nvt.namd

### ISSUE THREAD

**Issue by songyongshun** [HanatoK/Apoa1-Benchmark#2]
the margin is set to 8, which give a warning:
`Warning: MARGIN IS UNUSUALLY LARGE AND WILL LOWER PERFORMANCE
`
I change it to 0, and the performance is doubled. 
I also checked the parameter in official package as find in https://www.ks.uiuc.edu/Research/namd/utilities/.
They also have a margin of 0, though the force field is Charmm22.

**Comment by HanatoK** [comment]
@songyongshun In NAMD 3.0 alpha, it was suggested to set to 4 (see https://www.ks.uiuc.edu/Research/namd/alpha/3.0alpha/), but in a longer simulation time I still got error of margin violation as I remember (these benchmarks were uploaded a few years ago).

**Comment by songyongshun** [comment]
I tested it with namd2.13, maybe the differece comes from the different versions. 
I didn't notice the suggested margin value until you pointed it out. Thanks a lot.🙂
